import sys; sys.path.insert(0,'.')
exec(open('r35_updos.py').read().split("paths=[]; labels=[]")[0])
EG, GR, M, head, g = base(); t = Tree("elsa")
sc_ = bpy.data.objects["scalp"]; sc_.hide_render = False
smat = bpy.data.materials.new("scalp_raiz"); smat.node_tree.nodes['Principled BSDF'].inputs['Base Color'].default_value=(0.45,0.36,0.22,1); sc_.data.materials.append(smat)
def grp(n, out='Geometry', **kw):
    x = t.add('GeometryNodeGroup', group=GR[n])
    for k,v in kw.items(): x.inputs[k].default_value = v
    return t.chain(x, 'Geometry', out)
grp("GR Guias Procedurais", out='Guias', **{"Cabeça (colisão)": head, "Comprimento": 0.45, "Para trás": 0.4})
grp("GR Densidade Livre", Viewport=1.0)
grp("GR Mecha Estilizada", **{"Tamanho da mecha": 0.015})
TIE = (0.075, 0.06, -0.07)
grp("GR Rabo de Cavalo", **{"Cabeça (colisão)": head, "Amarração": TIE, "Até a amarração": 0.35, "Comprimento da cauda": 0.30, "Abertura": 0.012, "Para trás": -0.5})
grp("GR Trança Grossa", Raio=0.022, **{"Começa em": 0.38, "Cruzamentos": 1.0, "Espessura na ponta": 0.5, "Cabeça (colisão)": head})
grp("GR Cor por Mecha")
pr = t.add('GeometryNodeGroup', group=bpy.data.node_groups['Set Hair Curve Profile']); pr.inputs['Radius'].default_value=0.0006; t.chain(pr)
m = hair_mat("elsa", melanin=0.12, redness=0.35, roughness=0.3)
sm = t.add('GeometryNodeSetMaterial'); sm.inputs['Material'].default_value = m; t.chain(sm); apply_tree(g, t.finish())
print("INFO", stats(g).get('curves'), stats(g).get('points'))
p1 = shot("68_elsa_frente", res=420, samples=20, cam_loc=(0.35,-0.55,0.0), target=(0.03,0,-0.12), lens=40)
cam = bpy.context.scene.camera; cam.location = (0.62,0.25,0.02); d = Vector((0.03,0.02,-0.12))-cam.location; cam.rotation_euler = d.to_track_quat('-Z','Y').to_euler()
p2 = os.path.join(OUT, "68_elsa_lado.png"); render(p2)
print("SHEET", sheet([p1,p2], ["frente","lado"], os.path.join(OUT,"68_elsa_sheet.png"), cols=2, w=420))
